version: '3.7'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - nodeserver
    networks:
      - node-network
  
  nodeserver:
    container_name: nodeserver
    restart: always
    build:
      context: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    depends_on:
      - db
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: node index.js

  db:
    build: 
      context: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    networks:
      - node-network
    volumes:
      - /mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  node-network:
    driver: bridge